# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Pull bchew/dynamodump:latest docker image
        run: docker pull bchew/dynamodump:latest

      - name: Pull bchew/dynamodump:master docker image
        run: docker pull bchew/dynamodump:master

      - name: Pull bchew/dynamodump:version docker image
        run: docker pull bchew/dynamodump:v1.11.0

      - name: Pull bchew/jekyll-build:latest docker image
        run: docker pull bchew/jekyll-build:latest
